services:
  - docker

install:
  - docker build -t nominatim:xenial ./1.0
  - docker run -d -p 8080:8080 -e NOMINATIM_PBF_URL='http://download.geofabrik.de/asia/maldives-latest.osm.pbf' --name nominatim-xenial nominatim:xenial
  - docker build -t nominatim:trusty ./1.0/trusty
  - docker run -d -p 8081:8080 -e NOMINATIM_PBF_URL='http://download.geofabrik.de/asia/maldives-latest.osm.pbf' --name nominatim-trusty nominatim:trusty

before_script:
  - npm install newman --global

script:
  - docker ps | grep -q nominatim-xenial
  - ./tests/wait-for-http.sh http://localhost:8080/search
  - newman run tests/nominatim.postman_collection.json -e tests/nominatim-xenial.postman_environment.json
  - docker ps | grep -q nominatim-trusty
  - ./tests/wait-for-http.sh http://localhost:8081/search
  - newman run tests/nominatim.postman_collection.json -e tests/nominatim-trusty.postman_environment.json
